# Generated by Django 4.2.4 on 2023-10-25 08:55

from django.db import migrations


def find_the_group_of_the_person(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')

    persons = person.objects.all()

    for p in persons:
        if p.age <= 12:
            p.age_group = 'Child'
        elif 13 <= p.age <= 17:
            p.age_group = 'Teen'
        else:
            p.age_group = 'Adult'
    person.objects.bulk_update(persons, ['age_group'])


def reverse_age_group_default(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')

    default_age_group = person._meta.get_field('age_group').default

    persons = person.objects.all()

    for p in persons:
        p.age_group = default_age_group
    person.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_person'),
    ]

    operations = [
        migrations.RunPython(find_the_group_of_the_person, reverse_code=reverse_age_group_default)
    ]
