# Generated by Django 4.2.4 on 2023-10-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rariry',
            new_name='rarity',
        ),
    ]
