# Generated by Django 4.2.4 on 2023-10-25 10:24

from django.db import migrations


def set_new_value_to_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')

    items = item.objects.all()

    for i in items:
        if i.price <= 10:
            i.rarity = 'Rare'

        elif i.price <= 20:
            i.rarity = 'Very Rare'

        elif i.price <= 30:
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'
    item.objects.bulk_update(items, ['rarity'])


def reverse_rarity_to_default(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')

    default_rarity = item._meta.get_field('rarity').default

    items = item.objects.all()

    for i in items:
        i.rarity = default_rarity
    item.objects.bulk_update(items, ['rarity'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_rename_rariry_item_rarity'),
    ]

    operations = [
        migrations.RunPython(set_new_value_to_rarity, reverse_code=reverse_rarity_to_default)
    ]
