# Generated by Django 4.2.4 on 2023-10-25 10:33

from django.db import migrations


def calculate_phone_price(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')

    phones = phone.objects.all()

    for p in phones:
        p.price = len(p.brand) * 120
    phone.objects.bulk_update(phones, ['price'])


def set_category(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')

    phones = phone.objects.all()

    for p in phones:
        if p.price <= 750:
            p.category = 'Cheap'
        else:
            p.category = 'Expensive'
    phone.objects.bulk_update(phones, ['category'])


def union_category_and_price(apps, schema_editor):
    calculate_phone_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_default(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')

    phones = phone.objects.all()
    default_price = phone._meta.get_field('price').default

    default_category = phone._meta.get_field('category').default

    for p in phones:
        p.price = default_price
        p.category = default_category
    phone.objects.bulk_update(phones, ['price'])
    phone.objects.bulk_update(phones, ['category'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0016_smartphone'),
    ]

    operations = [
        migrations.RunPython(union_category_and_price, reverse_code=reverse_default)
    ]
