# Generated by Django 4.2.4 on 2023-10-25 21:40
import datetime

from django.db import migrations


def update_orders(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    for order in order.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + datetime.timedelta(days=3)
        elif order.status == 'Completed':
            order.warranty = '24 months'
        elif order.status == 'Cancelled':
            order.delete()
        order.save()


def reverse_update_orders(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    for order in order.objects.all():
        if order.status == 'Pending':
            order.delivery = None

        elif order.status == 'Completed':
            order.warranty = 'No warranty'
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0018_order'),
    ]

    operations = [
        migrations.RunPython(update_orders, reverse_code=reverse_update_orders),
    ]



